// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type Menu struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Slug  string      `json:"slug"`
	Items []*MenuItem `json:"items"`
}

type MenuItem struct {
	ID        string  `json:"id"`
	ParentID  *string `json:"parentId,omitempty"`
	Label     string  `json:"label"`
	ItemType  string  `json:"itemType"`
	RefID     *string `json:"refId,omitempty"`
	URL       *string `json:"url,omitempty"`
	SortOrder int     `json:"sortOrder"`
}

type Page struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Status      string  `json:"status"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}

type Post struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Excerpt     *string `json:"excerpt,omitempty"`
	Status      string  `json:"status"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}

type PostConnection struct {
	Posts []*Post `json:"posts"`
}

type Query struct {
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}
