version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: nextpress-postgres
    environment:
      POSTGRES_DB: nextpress
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - nextpress_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nextpress_pgdata: {}

